expr     = expr addsub term | term
term     = term multdiv factor | factor
factor   = number exp factor | number
number   = integer | floating | variable | lparen expr rparen | sqrt number
<lparen> = <"(">
<rparen> = <")">
addsub   = "+" | "-"
multdiv  = "/" | "*"
exp      = "^"
sqrt     = "√"
variable = "x" | "y" | "z"
floating = #"-{0,1}\d+\.\d+"
integer  = #"-{0,1}\d+"
