expr = expr addsub term | term
term = term multdiv factor | factor
factor = factor expsqrt number | number
number = integer | floating | lparen expr rparen
<lparen> = <"(">
<rparen> = <")">
addsub = "+" | "-"
multdiv = "/" | "*"
expsqrt = "^"
floating = #"-{0,1}\d+\.\d+"
integer = #"-{0,1}\d+"
